changelog:
  categories:
    - title: Breaking Changes
      labels:
        - semver:major
    - title: Features
      labels:
        - type:feature
    - title: Bug Fixes
      labels:
        - type:bug
    - title: Documentation
      labels:
        - type:docs
    - title: Security
      labels:
        - type:security
    - title: Quality and Automation
      labels:
        - type:quality
        - type:automation
  exclude:
    labels:
      - status:triage
